runtime: nodejs14

# Indique à App Engine d'installer les dépendances avec npm avant de démarrer l'application.
# Assurez-vous d'inclure un fichier package.json à la racine de votre projet.
# Vous pouvez également exclure node_modules/ si vous ne voulez pas que ces fichiers soient envoyés.
# skip_files:
#   - ^node_modules$

# Définit les variables d'environnement que votre application peut utiliser.
# Par exemple, si votre application nécessite une clé d'API, vous pouvez la spécifier ici.
# Par défaut, ces variables sont vides et vous devez les définir manuellement dans la Console GCP.
# env_variables:
#   MY_API_KEY: "your-api-key"

# Paramètres de déploiement supplémentaires, tels que le scaling, les ressources, etc., peuvent être spécifiés ici.
# Consultez la documentation de Google App Engine pour plus de détails sur ces options.
